import { SCORING_METHODS, SCORING_THRESHOLDS } from "../config/scoring";
import { ROLE_TARGETS, SQUAD_SIZE, normalizedFvm, safeMaximumBid, squadTotals, valueDifference } from "./squad";
import type { AgentInsight, ClassicRole, LeagueConfig, Player, PlayerBenchmark, SquadPlayer } from "../types";

const roleNames: Record<ClassicRole, string> = { P: "portieri", D: "difensori", C: "centrocampisti", A: "attaccanti" };

export function getAgentAdvice(config: LeagueConfig, squad: SquadPlayer[]): AgentInsight {
  if (!squad.length) return { type: "ADVICE", title: "Costruisci una base", verdict: "Il budget è ancora interamente disponibile.", evidence: [`Budget iniziale = ${config.budget} crediti`, "Slot occupati = 0 di 25"], threshold: SCORING_METHODS.roleComposition, nextAction: "Definisci un tetto per reparto e confronta il primo prezzo con il FVM normalizzato." };
  const totals = squadTotals(squad, config.budget);
  const slotsLeft = Math.max(SQUAD_SIZE - squad.length, 0);
  const averagePerSlot = slotsLeft ? Math.floor(totals.remaining / slotsLeft) : 0;
  if (totals.remaining < 0) return { type: "RISK", title: "Budget oltre il limite", verdict: `La rosa supera il budget di ${Math.abs(totals.remaining)} crediti.`, evidence: [`Spesi = ${totals.spent}`, `Budget configurato = ${config.budget}`], threshold: "Budget disponibile non può essere inferiore a 0", nextAction: "Rimuovi o sostituisci un acquisto prima di proseguire." };
  const missing = (Object.keys(ROLE_TARGETS) as ClassicRole[]).map((role) => ({ role, count: Math.max(ROLE_TARGETS[role] - totals.byRole[role], 0), ratio: totals.byRole[role] / ROLE_TARGETS[role] })).filter((entry) => entry.count > 0).sort((a, b) => a.ratio - b.ratio || b.count - a.count)[0];
  const expectedSpend = Math.round((squad.length / 25) * config.budget);
  const paceBuffer = Math.round(config.budget * SCORING_THRESHOLDS.spendPaceBufferShare);
  if (totals.spent > expectedSpend + paceBuffer && missing) return { type: "WARNING", title: "Ritmo di spesa alto", verdict: "La spesa è avanti rispetto al completamento della rosa.", evidence: [`Spesi = ${totals.spent}`, `Spesa lineare attesa = ${expectedSpend}`, `Slot liberi = ${25 - squad.length}`], threshold: `Warning oltre spesa attesa + ${paceBuffer} crediti`, nextAction: `Conserva margine per ${missing.count} ${roleNames[missing.role]} mancanti.` };
  const risks = squad.filter((entry) => { const delta = valueDifference(entry.paidPrice, normalizedFvm(entry.player, config)); return delta !== null && delta < SCORING_THRESHOLDS.budgetRiskMaximumPercent; });
  if (risks.length) return { type: "WARNING", title: "Hai pagato caro", verdict: `${risks.length} ${risks.length === 1 ? "acquisto è costato" : "acquisti sono costati"} sensibilmente più del riferimento FVM.`, evidence: risks.map((entry) => `${entry.player.name}: ${valueDifference(entry.paidPrice, normalizedFvm(entry.player, config))}% rispetto al FVM`), threshold: `Rischio prezzo sotto ${SCORING_THRESHOLDS.budgetRiskMaximumPercent}% · ${SCORING_METHODS.valueDifference}`, nextAction: "Cerca ora profili a prezzo equo o convenienti." };
  if (config.mode === "Mantra" && slotsLeft) return { type: "ADVICE", title: "Proteggi gli slot Mantra", verdict: `Restano ${slotsLeft} slot e una media sostenibile di ${averagePerSlot} crediti per acquisto.`, evidence: [`Budget disponibile = ${totals.remaining}`, `Offerta massima matematica oggi = ${safeMaximumBid(squad, config.budget)}`], threshold: "In Mantra i vincoli per ruolo dipendono dal regolamento della lega; Fanta007 applica budget e limite totale.", nextAction: "Confronta ruoli Mantra compatibili senza superare il massimo sostenibile." };
  if (missing) return { type: "ADVICE", title: `Priorità al reparto ${missing.role}`, verdict: `Mancano ${missing.count} ${roleNames[missing.role]}; la media sostenibile è ${averagePerSlot} crediti per slot residuo.`, evidence: [`Copertura ${missing.role} = ${totals.byRole[missing.role]}/${ROLE_TARGETS[missing.role]}`, `Budget disponibile = ${totals.remaining}`, `Offerta massima matematica oggi = ${safeMaximumBid(squad, config.budget)}`], threshold: SCORING_METHODS.roleComposition, nextAction: `Apri i ${roleNames[missing.role]} e confronta due o tre profili.`, recommendedRole: missing.role };
  return { type: "ADVICE", title: "Struttura completa", verdict: "Tutti i 25 slot della rosa di riferimento sono coperti.", evidence: [`Slot = ${squad.length}/25`, `Budget disponibile = ${totals.remaining}`], threshold: SCORING_METHODS.roleComposition, nextAction: "Controlla gli acquisti sopra benchmark prima di concludere." };
}

export function getPlayerInsight(player: Player, benchmark: PlayerBenchmark, config: LeagueConfig): AgentInsight {
  if (player.fvm === 0) return { type: "RISK", title: "Qui il FVM non aiuta", verdict: "Il Listone assegna FVM zero: sarebbe fuorviante trattarlo come un vero prezzo di riferimento.", evidence: ["FVM / 1000 = 0", `QA = ${player.current_quotation}`], threshold: "FVM deve essere maggiore di 0 per produrre un benchmark economico", nextAction: "Valuta storico, ruolo e prezzo richiesto senza usare il FVM come tetto d’asta." };
  if (player.quotation_delta <= SCORING_THRESHOLDS.quotationDeclineMaximum) return { type: "WARNING", title: "Quotazione in discesa", verdict: `Il valore è sceso da ${player.initial_quotation} a ${player.current_quotation}. Non è una bocciatura automatica, ma è un segnale da leggere insieme a rendimento e concorrenza nel ruolo.`, evidence: [`QI = ${player.initial_quotation}`, `QA = ${player.current_quotation}`, `Delta = ${player.quotation_delta}`], threshold: `Attenzione quando delta QA ≤ ${SCORING_THRESHOLDS.quotationDeclineMaximum}`, nextAction: "Prima di fissare il prezzo massimo, confrontalo con due o tre alternative dello stesso ruolo." };
  const elite = benchmark.fvm_top_percent <= SCORING_THRESHOLDS.eliteRoleTopPercent;
  return { type: "ADVICE", title: elite ? "Profilo da prima fascia" : "Dove si colloca nel ruolo", verdict: elite ? `Per FVM è ${benchmark.fvm_rank}° su ${benchmark.role_total} tra i ${roleNames[player.role_classic]}: parte da un riferimento da prima fascia. Questo non significa pagarlo a qualsiasi cifra, ma il profilo merita attenzione.` : `Per FVM è ${benchmark.fvm_rank}° su ${benchmark.role_total} tra i ${roleNames[player.role_classic]}. È un dato utile per capire la fascia, poi il prezzo d’asta va pesato contro rendimento e alternative disponibili.`, evidence: [`FVM = ${player.fvm}`, `Percentile FVM = ${benchmark.fvm_percentile}%`, `FVM normalizzato = ${normalizedFvm(player, config)} su budget ${config.budget}`], threshold: elite ? `Fascia alta: Top ${SCORING_THRESHOLDS.eliteRoleTopPercent}% del ruolo` : SCORING_METHODS.roleBenchmark, nextAction: "Usa il FVM normalizzato come riferimento, poi decidi il rilancio in base a quanto questo profilo serve davvero alla tua rosa." };
}
